### ISSUE TITLE
API to write SMT solvers

### ISSUE THREAD

**Issue by c-cube** [mishun/minisat-rust#2]
First, thank you for this project, it is very nice to have a decent SAT solver in a modern language.

I think it would be interesting to have an API (in the library part) that allows one to plug a theory in the SAT solver (that is, some trait `Theory` that is given a slice of the trail after each decision+propagations, and can propagate/add clauses/raise a conflict on its own). The trait (with a default empty implementation that does nothing) could look like:

```rust
enum TheoryResult {
  Sat { propagations: Vec<Lit>, split_clauses: Vec<Clause> },
  Conflict { conflict_lemma: Clause }
}

trait Theory {
  /// check if given slice of newly decided/propagated literals compatible with theory
  fn on_propagate(&mut self, slice: &[Lit]) -> TheoryResult;
  
  /// check if full assignment is sat
  fn final_check(&mut self, full_trail: &[Lit]) -> TheoryResult; 
}
```

What do you think?

edit: the `propagations` field should contain a `Vec<(Lit, Clause)>` or something similar (each propagated lit must be backed by a theory lemma, could be potentially lazy but has to be there for conflict analysis). Also, a callback to be called upon backtracking is required.

**Comment by mishun** [comment]
I kinda know nothing about SMT solvers. Am I understanding correctly that key idea is to have different clause types (in addition to disjunctive ones) and probably different variable types? So Lit above is actually not the same Lit and Clause is not the same Clause (or ClauseRef, because minisat has an ersatz moving garbage collector and does not work with Clause directly)? Then we need to decide how to handle different clause types --- it is already trouble with just two original minisat's types (usual and learned) where I don't knot yet how to get rid of epic low level hacks with possible undefined behaviour everywhere.

If I got idea behind Theory trait correctly, it should be aware of current search state. Then why it has final_check? And how to handle conflict analysis, learning and decision heuristics?

**Comment by c-cube** [comment]
Note that I don't want to abuse your time if you are not interested!

To give more details (not that I am a throroughly experienced SMT writer, but still): the idea of SMT is to have some external _theory solver_ (i.e. not in minisat itself) that gives an additional meaning to the boolean literals. The literals are still considered as booleans in the SAT solver, the constraints are still clauses (no need to change) but the theory solver is responsible for checking whether the current boolean model is compatible with its interpretation of literals.

For instance, equality over uninterpreted constants would have literals of the form, say `f(a,b)=g(c)` (still considered as booleans by the SAT solver) and would reject the trail `[b=a, not(f(b,b)=d),g(c)=d]` because it is absurd, something the SAT solver cannot know. To reject this trail it would generate a theory lemma (a boolean clause that happens to be a theorem in the theory) `not(b=a) or not(g(c)=d) or f(b,b)=d`. The point of the `Theory` trait is to keep the theory informed of the choices/propagations made at the boolean level (as soon as possible) so that the theory can propagate or signal conflicts by adding a clause. `final_check` is useful for those theories that are not incremental (or that are only partially incremental) and delay consistency checking until a full boolean model has been found; `on_propagate` otoh is called often and allows the theory to signal conflicts earlier, and therefore to prune the search space.

The additional requirements on the SAT solver are, therefore:

- not performing simplifications that would eliminate some literals (even if those are trivial at the boolean level, the theory still needs to know their assignment)
- communicating with the theory after any decision/propagation/backjump and take into account the new clauses/propagations made by the theory in response (in a fixpoint). Those new clauses or propagations might trigger a conflict at any time. Conflict analysis is simply the normal clause resolution with the _lemma_ provided by the clause upon conflict, and learning proceeds as usual; heuristics can stay more or less similar (afaik) at first. More details can be found in e.g. [this paper](http://ftp.cs.nyu.edu/~barrett/pubs/BNO+06-TR.pdf).

On a slightly more metalevel, right now (almost) all SMT solvers are written in C or C++ and are quite monolithic. I think rust (+ cargo) has the opportunity to make it a bit safer and easier to write decently efficient solvers in a more modular way. Also, SMT as a library is a potentially very useful thing (many solvers provide it, but often in C); see also the success of Z3 as a tool.

**Comment by mishun** [comment]
Hmm, looks like I'm starting to get at least what SMT solver is :) Am I right that I should further read papers about DPLL(T)?

This minisat reimplementation is intended to be educational detailed illustration of how (relatively) modern SAT solver works (and so: easy to understand, modular, having as many invariants guaranteed at type level as possible and so on, while being relatively fast) so I am interested in extensions at least as a way of knowing how "modular, easy to understand ..." it actually is (and I thought about maybe adding features from more advanced solvers later). Although idea with trait from above looks a bit too much Java for me for now: library part is supposed to contain building blocks that minisat can be reimplemented with using only a few dozens of high level code lines (it is not completely there for now but I'm going to improve it). Then why not write another few dozens lines of high level code for new SMT solver + custom propagation? Change in propagation is not the only one anyway: we also need to remove simplification, prevent user from creating literals and clauses manually, maybe remove minisat's learned clause minimization (I'm not sure if it works fine with SMT) and probably something else. Also it is probably better from performance point of view: SAT solvers spend most of their time propagating and pointer hacks in my propagation code are even actually useful :).

If you need an interface exactly like above for some reason, I can add new "minisat with trait and without simplification" implementation of course --- it would not break anything and would be pretty easy.

**Comment by c-cube** [comment]
SMT solvers are very interesting, so if you're into that sort of things you should clearly read about them (e.g. read a bit about z3 and CVC4, they cover lots of theories and are widely used). If you want this project to be a good illustration of what a modern SAT solver is, it might be problematic to clutter it with SMT-specific interfaces (I don't think it would fit into a few dozens lines). For now I don't have the time, but maybe the proper way to go is to make an alternative project (starting from this one, but diverging) aiming at showing what a basic SMT infrastructure looks like — probably with a simpler boolean solver but a few basic theories and a SMTLib parser to make it able to solve basic problems. So please, don't spend time on this. I will close the issue for now :-)
